# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: plugin.proto for package 'proto'
# Original file comments:
# plugin.proto
# Defines the gRPC interface between gaia and the user defined
# pipelines (plugins). All rpc Methods are called from Gaia and
# executed in the plugin. 
#

require 'grpc'
require 'plugin_pb'

module Proto
  module Plugin
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'proto.Plugin'

      # GetJobs returns a stream of Job objects.
      # Used to expose jobs to gaia.
      rpc :GetJobs, Empty, stream(Job)
      # ExecuteJob signals the plugin to execute the given job.
      # Used to execute one job from a pipeline.
      rpc :ExecuteJob, Job, JobResult
    end

    Stub = Service.rpc_stub_class
  end
end
